AWSTemplateFormatVersion: 2010-09-09
Description: Stack for Monetize service
  
Parameters:
  
    DynamoDbTableName: 
      Type: String
      Description: The name of your Api.
      MaxLength: 350
      MinLength: 1
  
    DynamoDbTableARN: 
      Type: String
      Description: The name of your Api.
      MaxLength: 350
      MinLength: 1

    TopicArn: 
      Type: String
      Description: The name of your Api.
      MaxLength: 350
      MinLength: 1

# Metadata:
  
# Mappings:
  
# Conditions:
  
Resources:

  EmailDevSubscription:
    Type: "AWS::SNS::Subscription"
    Properties:
      Endpoint: sordier.andrew@gmail.com
      # FilterPolicy: |
      #   {
      #     "Issue":["violent or repulsive content"]
      #   }
      Protocol: email
      TopicArn: !Ref TopicArn

  CreatedClosedJobRequestEvent: 
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: ./createdClosedJobRequestEvent.yaml
      Parameters: 
        TopicArn: !Ref TopicArn

        FunctionName: CreatedClosedJobRequestEvent
        FunctionDescription: Lambda processing created job request events.
        FunctionHandler: index.handler
        FunctionMemorySize: '1280'
        FunctionRuntimeVersion: nodejs12.x
        FunctionTimeout: '30'
        ServiceTag: Monetize
        ApplicationTag: Textras
        PathRole: /lambda/


  UpdatedClosedJobRequestEvent: 
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: ./UpdatedClosedJobRequestEvent.yaml
      Parameters: 
        TopicArn: !Ref TopicArn

        FunctionName: UpdatedClosedJobRequestEvent
        FunctionDescription: Lambda processing updated job request events ( winner assignement).
        FunctionHandler: index.handler
        FunctionMemorySize: '128'
        FunctionRuntimeVersion: nodejs12.x
        FunctionTimeout: '10'
        ServiceTag: Monetize
        ApplicationTag: Textras
        PathRole: /lambda/

  ExpiredClosedJobEvent: 
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: ./expiredClosedJobEvent.yaml
      Parameters: 
        DynamoDbTableName: !Ref DynamoDbTableName
        TopicArn: !Ref TopicArn

        FunctionName: ExpiredClosedJobEvent
        FunctionDescription: Lambda processing expired job events.
        FunctionHandler: index.handler
        FunctionMemorySize: '128'
        FunctionRuntimeVersion: nodejs12.x
        FunctionTimeout: '10'
        ServiceTag: Monetize
        ApplicationTag: Textras
        PathRole: /lambda/

  ClosedJobPushNotificationEvent: 
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: ./ClosedJobPushNotificationEvent.yaml
      Parameters: 
        DynamoDbTableName: !Ref DynamoDbTableName
        DynamoDbTableARN: !Ref DynamoDbTableARN
        # TransactionTableName: !Ref TransactionTableName
        # TransactionTableARN: !Ref TransactionTableARN
        TopicArn: !Ref TopicArn

        FunctionName: ClosedJobPushNotificationEvent
        FunctionDescription: Lambda processing push notifications.
        FunctionHandler: index.handler
        FunctionMemorySize: '128'
        FunctionRuntimeVersion: nodejs12.x
        FunctionTimeout: '10'
        ServiceTag: Monetize
        ApplicationTag: Textras
        PathRole: /lambda/

# Outputs: